INSERT INTO Packages (Nom, Description) VALUES
    ('express', 'Fast, unopinionated, minimalist web framework for Node.js.'),
    ('react', 'A JavaScript library for building user interfaces.'),
    ('vue', 'The Progressive JavaScript Framework.'),
    ('angular', 'A platform for building mobile and desktop web applications.'),
    ('lodash', 'A modern JavaScript utility library delivering modularity, performance, and extras.'),
    ('axios', 'Promise-based HTTP client for the browser and Node.js.'),
    ('moment', 'A lightweight JavaScript date library for parsing, validating, manipulating, and formatting dates.'),
    ('jsonwebtoken', 'Implementation of JSON Web Tokens.'),
    ('mongoose', 'MongoDB object modeling tool designed to work in an asynchronous environment.'),
    ('typescript', 'JavaScript with syntax for types.'),
    ('jest', 'Delightful JavaScript testing framework with a focus on simplicity.'),
    ('webpack', 'A module bundler for modern JavaScript applications.'),
    ('babel', 'A JavaScript compiler.'),
    ('socket.io', 'Enables real-time, bidirectional, and event-based communication.'),
    ('eslint', 'A tool for identifying and reporting on patterns in JavaScript.'),
    ('chalk', 'Terminal string styling done right.'),
    ('cors', 'Middleware for enabling Cross-Origin Resource Sharing.'),
    ('body-parser', 'Node.js body parsing middleware.'),
    ('npm', 'The package manager for JavaScript.'),
    ('yarn', 'A fast, reliable, and secure dependency management tool.');
